# Generated by Django 4.1.1 on 2022-09-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField(verbose_name='Идентификатор в ВК')),
                ('photo', models.CharField(max_length=255, verbose_name='Изображение пользователя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия пользователя')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь ВКонтакте',
                'verbose_name_plural': 'Пользователи ВКонтакте',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
