# Generated by Django 4.1.1 on 2022-09-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='vk_id',
            field=models.IntegerField(unique=True, verbose_name='Идентификатор в ВК'),
        ),
    ]
